---
- hosts: macbook
  tasks:

  # - name: install homebrew packages
  #   homebrew:
  #     name: "{{ item }}"
  #     state: present
  #   loop: 
  #     - autoconf
  #     - automake
  #     - bitwarden
  #     - bash
  #     - boost
  #     - clang-format
  #     - cmake
  #     - coreutils
  #     - dos2unix
  #     - fping
  #     - gnupg
  #     - go
  #     - htop
  #     - p7zip
  #     - pbzip2
  #     - pcre
  #     - pigz
  #     - tmux
  #     - vim
  #     - w3m
  #     - wget
  #     - zsh
  #     - zsh-syntax-highlighting
  #     - node
  #     - npm
  #     - docker-machine-driver-hyperkit
  #     - cowsay
  #     - angular-cli
  #     - kubernetes-cli
  #     - kubernetes-helm
  #     - redis
  #     - tree
  #     - jq
  #     - yarn
  #   ignore_errors: true

  #The below will fail if you installed any of the programs outside of brew
  # - name: install homebrew casks
  #   homebrew_cask:
  #     name: "{{ item }}"
  #     state: present
  #   loop:
  #     - docker
  #     - discord
  #     - firefox
  #     - google-chrome
  #     - fantasy-grounds
  #     - steam
  #     - iterm2
  #     - macpass
  #     - postman
  #     - visual-studio-code
  #     - wireshark
  #     - flux
  #   ignore_errors: true

  - name: Disable Creation of .DS_Store
    shell: "defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true"

  - name: create needed directories
    file:
      path: "{{ item }}"
      state: directory
      mode: "0700"
    loop:
      - "~/Library/KeyBindings"

  - name: Map Home and End Keys
    template:
      backup: true
      dest: "~/Library/KeyBindings/DefaultKeyBinding.dict"
      src: "templates/keyBindings"

  - name: Find brew path
    shell: brew --prefix
    register: brew_path

  - name: Deploy Updated Profiles
    template:
      backup: true
      dest: "~/.{{ item }}rc"
      src: "templates/{{ item }}_profile"
    loop:
      - "zsh"
      - "bash"

  - name: Setup Oh My Zsh
    ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    args:
      creates: "~/.oh-my-zsh/oh-my-zsh.sh"

  - name: Download Zsh Theme
    get_url:
      url: https://raw.githubusercontent.com/caiogondim/bullet-train-oh-my-zsh-theme/master/bullet-train.zsh-theme
      dest: "~/.oh-my-zsh/custom/themes/bullet-train.zsh-theme"

  # - name: Setup Fonts
  #   ansible.builtin.copy:
  #     src: fonts/*.ttf
  #     dest: "~/Library/fonts/"
  #     owner: pclemens
  #     group: staff
  #     mode: '0755'

  - name: Get list of Fonts
    command: "find /Users/pclemens/GIT/macossetup/fonts -type f"
    register: files_to_copy

  - name: debug
    debug:
      var: "{{ files_to_copy.stdout_lines }}"

  - name: Setup Fonts
    copy:
      src: "{{ item }}" 
      dest: "~/Library/fonts/"
      owner: pclemens
      group: staff
      mode: 0750
    loop:
    - "{{ files_to_copy.stdout_lines }}"

  - name: Install VS Code Extentions
    shell: code --install-extension {{ item }}
    loop:
     - "eamodio.gitlens"
     - "esbenp.prettier-vscode"
     - "coenraads.bracket-pair-colorizer-2"
     - "docsmsft.docs-markdown"
     - "oderwat.indent-rainbow"
     - "yzhang.markdown-all-in-one"
     - "ms-vscode.sublime-keybindings"
     - "redhat.vscode-yaml"